<?php

    // init
    require_once "./custom/tool/initialize/system_tables.php";

    // update
    require_once "./custom/tool/update/add_sub_update.php";
    require_once "./custom/tool/update/job_station_update.php";
    require_once "./custom/tool/update/page_file_rename.php";
    require_once "./custom/tool/update/jc1tojc2_update.php";
    require_once "./custom/tool/update/reset_apply_pos.php";